version: "3.8"
services:
  lordmobileweb: 
    image: php:7.4-apache
    ports: 
        - 8090:80
    volumes: 
        - ../:/var/www/html
    links: 
        - lordmobilesql

  lordmobilesql:
    image: mysql:5.6
    volumes: 
        - ./mysql/data:/var/lib/mysql
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: lordmobile
        MYSQL_DATABASE: lordmobiledb
        MYSQL_PASSWORD: lordmobile
    #command: mysql lordmobiledb -u MYSQL_USER -p MYSQL_PASSWORD < lordmobiledb.sql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment: 
        MYSQL_ROOT_PASSWORD: root
        #PMA_USER: admin
        #PMA_PASSWORD: admin
        PMA_HOST: lordmobilesql
    links: 
        - lordmobilesql
    ports: 
        - 8082:80


